project_id = "tzdpqwkbkuqypzzuphmt"

[functions.admin-auth]
verify_jwt = false

[functions.institution-auth]
verify_jwt = false

[functions.institution-signup]
verify_jwt = false

[functions.create-institution-account]
verify_jwt = false

[functions.emergency-support]
verify_jwt = true
